[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "setuptools_scm[toml]>=3.4",
    "twine",
]

[tool.setuptools_scm]
write_to = "src/spihole/_version.py"
local_scheme = "dirty-tag"
fallback_version = "0.0.4"
